.TH "q2_zombie.c" 3 "Thu Aug 1 2019" "Computer Networks Laboratory Lab Assignment-2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
q2_zombie.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Computer Networks Laboratory Lab Assignment-2 from the source code\&.
