.TH "server.c" 3 "Thu Aug 1 2019" "Computer Networks Laboratory Lab Assignment-2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.c
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORT\fP   8080"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char const *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PORT   8080"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char const * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Computer Networks Laboratory Lab Assignment-2 from the source code\&.
